insert into public.exercicios (nome, grupo_muscular, equipamento) values
  ('Supino Reto', 'Peito', 'Barra'),
  ('Supino Inclinado', 'Peito', 'Halteres'),
  ('Crucifixo Máquina', 'Peito', 'Máquina'),
  ('Paralelas', 'Peito', 'Peso Corporal'),
  ('Barra Fixa', 'Costas', 'Peso Corporal'),
  ('Puxada Frontal', 'Costas', 'Máquina'),
  ('Remada Curvada', 'Costas', 'Barra'),
  ('Remada Baixa', 'Costas', 'Cabo'),
  ('Agachamento Livre', 'Pernas', 'Barra'),
  ('Leg Press 45', 'Pernas', 'Máquina'),
  ('Cadeira Extensora', 'Pernas', 'Máquina'),
  ('Mesa Flexora', 'Pernas', 'Máquina'),
  ('Stiff', 'Pernas', 'Barra'),
  ('Elevação Pélvica', 'Glúteos', 'Barra'),
  ('Cadeira Abdutora', 'Glúteos', 'Máquina'),
  ('Desenvolvimento Halteres', 'Ombros', 'Halteres'),
  ('Elevação Lateral', 'Ombros', 'Halteres'),
  ('Encolhimento de Ombros', 'Ombros', 'Barra'),
  ('Rosca Direta', 'Braços', 'Barra'),
  ('Rosca Alternada', 'Braços', 'Halteres'),
  ('Tríceps Corda', 'Braços', 'Cabo'),
  ('Tríceps Francês', 'Braços', 'Halteres'),
  ('Prancha Isométrica', 'Abdômen', 'Peso Corporal'),
  ('Abdominal Supra', 'Abdômen', 'Peso Corporal'),
  ('Elevação de Pernas', 'Abdômen', 'Peso Corporal'),
  ('Panturrilha em Pé', 'Panturrilha', 'Máquina'),
  ('Panturrilha Sentado', 'Panturrilha', 'Máquina'),
  ('Corrida na Esteira', 'Cardio', 'Máquina'),
  ('Bicicleta Ergométrica', 'Cardio', 'Máquina')
on conflict (nome, grupo_muscular) do nothing;
